---
- name: Ensure iptables is installed (RedHat).
  yum: pkg=iptables state=installed
  when: ansible_os_family == 'RedHat'

- name: Ensure iptables is installed (Debian).
  apt: pkg=iptables state=installed
  when: ansible_os_family == 'Debian'

- name: Make IP block directories
  file: state=directory owner=root group=root mode=0744 path={{ item }}
  with_items:
  - /etc/ipblocks
  - /etc/ipblocks/6
  - /etc/ipblocks/4

- name: Unarchive IP block zone files (thanks, ipdeny.com!)
  unarchive: src="{{ item.url }}" dest="{{ item.dest }}"
  with_items:
  - { url: 'ipv4-zones.tgz', dest: '/etc/ipblocks/4' }
  - { url: 'ipv6-zones.tgz', dest: '/etc/ipblocks/6' }

- name: Flush iptables the first time playbook runs.
  command: iptables -F creates=/etc/init.d/firewall

- name: Copy firewall script into place.
  template: src=firewall.bash.j2 dest=/etc/firewall.bash owner=root group=root mode=0744
  notify: restart firewall

- name: Copy firewall init script into place.
  template: src=firewall.j2 dest=/etc/init.d/firewall owner=root group=root mode=0755

- name: Ensure the firewall is enabled and will start on boot.
  service: name=firewall state=started enabled=yes
